# Generated by Django 4.0.6 on 2022-07-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_student_email_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('B', 'borrowed'), ('A', 'Available')], default='d', help_text='Book availability', max_length=1)),
                ('book_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myApp.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
